### ISSUE TITLE
[FEA] Implement nvstrings.ftos (float to string)

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/custrings#112]
Implement a float to string function similar to `itos`. Would ideally like to be able to pass a null bitmask here as well so that we can differentiate between `nan` and `null`.

**Comment by davidwendt** [comment]
Found a simpler implementation than dragon4 and compares well to 10 significant digits.
Very large and very small numbers are converted to scientific notation. The stof method has been updated to handle scientific notation.
Fixed in PR #194

**Comment by beckernick** [comment]
@davidwendt we should update the docs to reflect the fact that `ftos` converts to scientific notation by default
