### ISSUE TITLE
[FEA] nvstrings.split ability to strip beginning / before whitespace

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/custrings#128]
By default if you don't pass a pattern to `pandas.Series.str.split` it strips all whitespace before and after the strings:
```python
pd_series = pd.Series(['a b', ' c ', '   d', 'e   ', 'f'])
print(pd_series.str.split(pat=None, expand=True))

# Got
   0     1
0  a     b
1  c  None
2  d  None
3  e  None
4  f  None
```

Any chance we could add some type of parameter to allow this behavior?

**Comment by davidwendt** [comment]
Apparently pandas uses Python `str.split()` which has this behavior:
```
If sep is not specified or is None, a different splitting algorithm is applied: runs of consecutive 
whitespace are regarded as a single separator, and the result will contain no empty strings at the start or
end if the string has leading or trailing whitespace. 
Consequently, splitting an empty string or a string consisting of just whitespace with a None separator returns [].
```


https://docs.python.org/3/library/stdtypes.html#str.split

**Comment by randerzander** [comment]
Yes, that is a commonly relied upon behavior for Python's native string split functionality.

We should support it as well.
