### ISSUE TITLE
[FEA] Float to strings function : float_to_string

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/custrings#146]
# [FEA] Float to strings function : float_to_string

Request feature  needed to create strings from an array of float32/float64 values .

Need something similar to [itos function](https://github.com/rapidsai/custrings/blob/branch-0.3/python/nvstrings.py#L186). 

```
def itos(values, count=0, nulls=None, bdevmem=False)
```

**Comment by davidwendt** [comment]
duplicate of #112 
please any new information to that issue
