### ISSUE TITLE
Precompiler ifndef flags in header files

### ISSUE THREAD

**Issue by felipeblazing** [rapidsai/custrings#165]
Is there a reason why there are not ifndef precompiler flags in NVCategory.h, NVStrings.h ?
something like
`#ifndef NVIDIA_NV_STRINGS_H_NVStrings
#def NVIDIA_NV_STRINGS_H_NVStrings `

**Comment by davidwendt** [comment]
I've added `#pragma once` to the top of all the header files. This tells the compiler to include this file only once and is faster than the ifndef construct which requires the compiler to open and process the file each time.
