### ISSUE TITLE
[FEA] Support element-wise string equality comparisons

### ISSUE THREAD

**Issue by randerzander** [rapidsai/custrings#169]
Pandas Example:
```
import pandas as pd

chars1 = ['a', 'b', 'c', 'd']
chars2 = ['a', 'b', 'd', 'e']
pdf = pd.DataFrame({'chars1': chars1, 'chars2': chars2})

pdf['chars1'] == pdf['chars2']
```
Result:
```
0     True
1     True
2    False
3    False
dtype: bool
```

This is most similar to nvstrings.compare, which compares each string entry to a single static value.

It also returns 0 for an exact match, and non-zero values to indicate larger/smaller first non-matching chars.

I propose the following:
1. Add an arg to have returned result be 1 for a match, 0 for non-match
2. Support passing a second nvstrings object to perform comparisons against on a per element basis

nvstrings proposed api:
```
import nvstrings

chars1 = ['a', 'b', 'c', 'd']
chars2 = ['a', 'b', 'd', 'e']

strs1 = nvstrings.to_device(chars1)
strs2 = nvstrings.to_device(chars2)

strs1.compare(strs2, boolMatch = True)
```
Expected Result:
```
[1, 1, 0, 0]
```

@kkraus14 fyi. Do you agree with this proposed API? Does it get you what you need for cuDF to consume?

**Comment by davidwendt** [comment]
Since this is completely different function with different parameters and behavior, I propose creating a new API like `compare_strings` instead of overloading the existing `compare` function.

**Comment by randerzander** [comment]
Ok about creating a new function. How about calling it `compare_nvstrings`?

**Comment by davidwendt** [comment]
I'd like to keep it consistent with other methods (add_strings, remove_strings, find_multiple) and with nvcategory (to_strings, gather_strings, from_strings) where plural _strings_ is an nvstrings instance.
Also, the behavior here is much closer to `match()` which returns booleans. Maybe this should be an overload of that instead (or match_strings).
I think `compare()` has a connotation in most languages of it being able to use it for sorting/ordering.

**Comment by davidwendt** [comment]
The new `match_strings` method was added in PR #176
