### ISSUE TITLE
[FEA] Add levenshtein edit distance function

### ISSUE THREAD

**Issue by randerzander** [rapidsai/custrings#170]
Calculating ["edit distance"](https://github.com/aflc/editdistance) between string values is useful.

nvstrings should add an `edit_distance` function.

It should support calculating edit distance to both a static string, and element-wise between two nvstrings instances.

**Comment by randerzander** [comment]
We're starting to stack up requests for more complex string functionality that probably doesn't make sense to be in cuStrings directly.

@dantegd is this something you'd want to pull into a cuML preprocessing function, alongside bag of words and vocabulary extraction from the [rave module](https://github.com/rapidsai/custrings/blob/branch-0.4/python/rave.py)?

**Comment by beckernick** [comment]
In terms of prioritization string distance algorithms, I would think that supporting Levenshtein and Jaro-Winkler would cover a substantial portion of workflows. Soundex as well.

**Comment by davidwendt** [comment]
Levenshtein edit distance function added to rave/nvtext in PR #180
