### ISSUE TITLE
Makefile in cpp folder is outdated

### ISSUE THREAD

**Issue by IceTDrinker** [rapidsai/custrings#184]
Hello,

I tried to build the project for C++, but the instructions date back to 0.2.0, the Makefile is outdated (std is c++11 and should be c++14) and builds a swiss-cheese shared object for the 0.3.0 release. I see it is still the case on the master branch.

Using the build instructions for python (excluding activating the environment) worked on my machine. I guess there might be python package dependencies but I must have had the packages already installed.

Installing the 2 c++ shared object generated this way allows to use custrings properly.

A side note: cudf includes <nvstrings/NVStrings.h>, once custrings is installed creating a symlink nvstrings -> custrings in the /usr/local/include directory allows to use custrings properly for cudf.

Cheers.

**Comment by davidwendt** [comment]
You are correct. This file needs to be updated or removed. Either way, the instructions need to be fixed as well.

**Comment by davidwendt** [comment]
Fixed in PR #216
