### ISSUE TITLE
nrows support in cudf.io.csv.read_csv() is causing an exception

### ISSUE THREAD

**Issue by kenhester** [rapidsai/custrings#191]
**Describe the bug**
When calling cudf.io.csv.read_csv_strings() using nrows to read a file in chunks, I get a thrust exception.

Exception:
```
nvs-idx: computing sizes: cudaErrorIllegalAddress(77):an illegal memory access was encountered
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  device free failed: an illegal memory access was encountered
```

**Steps/Code to reproduce bug**
Full python code in file attached

Snippet:
```
while True:
    frame = cudf.io.csv.read_csv_strings(file, quoting=False, doublequote=False, names=names, dtype=dtypes, skiprows=skip_rows, nrows=rows_to_read)
    skip_rows += rows_to_read
...
    if rows_read < rows_to_read:
        break

```

**Expected behavior**
Read the file in chunk windows.  For last chunk, return remaining rows without exception.

**Environment details (please complete the following information):**
Latest NGC RAPIDS CUDA 10 Container (0.5.1)
 

**Additional context**
Data file is large and private; provided on request.

Program File:
[load_pos_file.zip](https://github.com/rapidsai/cudf/files/2906448/load_pos_file.zip)

**Comment by davidwendt** [comment]
@vuule The terminate occurs inside one the RMM_FREE calls inside NVStrings::replace()? Any suggestions on how to prevent this?

**Comment by davidwendt** [comment]
Does not look possible to stop the terminate if illegal memory is being passed into NVStrings. See this conversation: https://nvidia.slack.com/messages/C7MFRGM6H/p1555356531003300
I will add some code to try to force this to be an exception but the very next call to CUDA in libcudf or anywhere in the process will fail with the same error. As mentioned in the slack-thread, this particular error cannot be recovered and the process must be restarted.

**Comment by davidwendt** [comment]
Added additional checking for bad pointers in PR #226
