### ISSUE TITLE
[BUG] Support slice replacing when start = stop

### ISSUE THREAD

**Issue by beckernick** [rapidsai/custrings#198]
### Description

It would be very useful to insert a specified pattern of arbitrary length into any position in all strings. As @davidwendt pointed out, when `start`=`stop` the `slice_replace` method does not do any replacement:

nvstrings:
```
import nvstrings
s = nvstrings.to_device(["hello","goodbye","well"])
print(s.slice_replace(0,0,'temp '))
['hello', 'goodbye', 'well']
```

pandas:
```
import pandas as pd
s = pd.Series(["hello","goodbye","well"])
s.str.slice_replace(0,0,'temp ')
0      temp hello
1    temp goodbye
2       temp well
dtype: object
```

I'm not sure if there is a good workaround from the Python layer, as our replace cannot operate on the beginning of the string without also consuming the character at index 0 if we cannot have start=stop.

**Comment by davidwendt** [comment]
This does not look like an appropriate feature for the pad methods (pad, ljust, rijust, center, zfill).
The `slice_replace()` method _should_ allow you to insert arbitrary text into all the strings in any position.
```
import pandas as pd
s = pd.Series(["hello","goodbye","well"])
s.str.slice_replace(0,0,'temp ')
0      temp hello
1    temp goodbye
2       temp well
dtype: object
```
So there appears to be inconsistency with `nvstrings.slice_replace()` which does not insert the string when start=stop.

**Comment by beckernick** [comment]
Great point @davidwendt . Will update this issue to reflect this.
