### ISSUE TITLE
[FEA] Replace/Subsitute only matched pattern with Backref

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/custrings#206]
## [FEA] Replace only the matched pattern with Backref

As a user i would like to have  a feature where i can replace only the matched string (pattern) in each string with another string (repl)  containing  back references, while keeping the non matched parts.

Currently the [replace_with_backref](https://github.com/rapidsai/custrings/blob/branch-0.4/python/nvstrings.py#L1403)  function  creates a new string with the extracted elements found using the pat expression and discards the non matched parts . 

#### Example:
```python
import nvstrings
import re
line = "test-string"
strs = nvstrings.to_device([line])

pattern = "([a-z])-([a-z])"
repl_regex = r"\1 \2"
print("{}".format(re.sub(pattern, repl_regex, line)))
print("{}".format(strs.replace_with_backrefs(pattern, repl_regex).to_host()[0]))
```

#### Current Output
```python
test string
t s
```
I want a function that gives the output as "test string" for above pattern.

### Multiple Match Ambiguity
Currently the replace_with_backrefs only replaces the first match (i guess) and the other matches are discarded which seems ambiguous.

#### Example:
```python
import nvstrings

line = "test-string-again"
pattern = "([a-z])-([a-z])"
repl_regex = r"\1 \2"

strs = nvstrings.to_device([line])
print("{}".format(strs.replace_with_backrefs(pattern, repl_regex).to_host()[0]))

```
#### Current Output
```
t s
```

### Naming Confusion

The function name my be confusing to a new user. As a new user i though that the [replace_with_backref](https://github.com/rapidsai/custrings/blob/branch-0.4/python/nvstrings.py#L1403)  will behave like [replace](https://github.com/rapidsai/custrings/blob/branch-0.4/python/nvstrings.py#L1378) function in which we only replace the matched pattern and keep other parts of the string.

In replace_with_backref we discard the non matches. Some thing that i did not expect.

### Advice needed for workaround  :
I am using the below script for replacement without discarding. This does not extend to multiple matches. It would awesome if some one could help me with extending it. 

```python
import nvstrings

line = "test-string-bla"
pattern = "(.*?)([a-z])-([a-z])(.*)"
strs = nvstrings.to_device([line])
repl_regex = r"\1\2 \3\4"
print("{}".format(strs.replace_with_backrefs(pattern, repl_regex).to_host()[0]))
```
Output
```
test string-bla
```

**Comment by davidwendt** [comment]
For the first example if you change the
```
pattern = "([a-z])-([a-z])"
```
to
```
pattern = "([a-z]*)-([a-z]*)"
```
then the output would be `test string` instead of `t s`.

Still looking at why multiple replaces are not occurring.

**Comment by VibhuJawa** [comment]
Thanks for looking into this.

I think the  ``` pattern = "([a-z]*)-([a-z]*)" ``` will only create 2 groups and wont extend to multiple matches .  

Link to the regex example in use: https://regex101.com/r/UShWXo/1
