### ISSUE TITLE
[BUG]  numpy array and boolean indexes incorrect result for sublist/gather.

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/custrings#208]
# [BUG]  numpy array and boolean indexes support for sublist/gather.

The gather/sublist function does not give correct result for numpy arrays or bool arrays.
It  may be useful to add support for this  or at least raise a TypeError  .  

## Reproduction Code
```python
import nvstrings
import numpy as np

strs = nvstrings.to_device(["a","b","c"])

index_ls = [0,2]
index_np_ar = np.asarray(index_ls)
bool_mask = [True,False,True]

print("ls_result {}".format(strs.gather(index_ls)))
print("np result {}".format(strs.gather(index_np_ar)))
print("bool_result {}".format(strs.gather(bool_mask)))
```

### Output
```
ls_result ['a', 'c']
np result ['a', 'a', 'c', 'a']
bool_result ['b', 'a', 'b']
```

The correct result  ['a', 'c']

**Comment by davidwendt** [comment]
All input arrays are expected to be int32.
The np.asarray must be created using dtype=int32. The default is int64.
Use this instead: ` index_np_ar = np.asarray(index_ls,dtype=np.int32)`
The bool_mask array converts the True, False to integers 0,1 respectively.
So this is working correctly. I can fix the documentation if you think that is necessary.

**Comment by VibhuJawa** [comment]
Yup, It works correctly with int32.  

### Regarding int32 and inst64

It would be good to document that  np.asarray must be created using dtype=int32. 
at the [function](https://rapidsai.github.io/projects/nvstrings/en/0.4.0/api.html#nvstrings.nvstrings.sublist) 

The indices should not go above int32 range but I still think it  may  a good to have a typecheck/typecasting at [line](https://github.com/rapidsai/custrings/blob/branch-0.4/python/nvstrings.py#L2299) or possibly something even downstream at pyniNVStrings.n_gather .

### Regarding Booean Masks
I think it would be good to a feature that allows boolean masking as its a common operation. 
I am thinking something like in numpy :

```python
import nvstrings
import numpy as np

bool_mask = [True,False,True]
strs = nvstrings.to_device(["a","b","c"])
ar  = np.asarray([1,2,3])
print(ar[bool_mask])
print(strs[bool_mask])

```
Current Output
```
[1 3]
['b', 'a', 'b']
```

Desired output:
```
['b','c']
```

This is not priority as the work around is simple but still good to have and helpful for users new to  custrings. 

Current Work Around:
```python
bool_mask = [True,False,True]
sub_ls = [i for i, bool_mask in enumerate(bool_mask) if bool_mask]

print(strs[sub_ls])
```

**Comment by davidwendt** [comment]
You are welcome to open a feature issue to support boolean types for gather. This would be a new enhancement and not a bug in the existing implementation.

We could repurpose this issue for improving the type-checking.

**Comment by VibhuJawa** [comment]
Raised feature issue, #219 for boolean type support.

**Comment by davidwendt** [comment]
Added more type-checking in PR #234
