### ISSUE TITLE
[FEA] Add devptr argument to nvcategory.keys

### ISSUE THREAD

**Issue by randerzander** [rapidsai/custrings#214]
After generating an nvcategory from nvstrings, I often want to further analyze just the unique keys with nvstrings functions.

Can we add an optional devptr argument to the [nvcategory.keys](https://github.com/rapidsai/custrings/blob/branch-0.4/python/nvcategory.py#L211) method?

Or, add a new method which returns a new nvstrings instance containing the list of keys?

**Comment by davidwendt** [comment]
I think the keys() method already does this. Maybe I'm misunderstanding your issue.
```
import nvcategory, nvstrings
s = nvstring.to_device([["eee","aaa","eee","dddd"])
c = nvcategory.from_strings(s)
keys = c.keys()
```
The `keys` variable here is an nvstrings instance.

**Comment by randerzander** [comment]
You're right, I didn't look closely enough at the return type. Thanks!
