### ISSUE TITLE
[BUG] custrings.cuh `bytes` parameters should be `size_t`

### ISSUE THREAD

**Issue by harrism** [rapidsai/custrings#215]
There is a mismatch in the type of the `bytes` parameter between the declarations of all functions in custring.cuh and their implementations. The declaration uses `unsigned int` while the implementation uses `size_t`. I think all should be `size_t`.

https://github.com/rapidsai/custrings/blob/24e83d89dad1d06ed50e0f22dd5b3df9b286f196/cpp/src/custring.cuh#L21-L33

**Comment by davidwendt** [comment]
Thanks Mark. These functions are not actually being used yet. They are future placeholders with code logic I did not want to lose. Regardless, they should and will be fixed. I can't tell you how many times I've looked at this code and not noticed this issue though.

**Comment by davidwendt** [comment]
Fixed in PR #217
