### ISSUE TITLE
[FEA] Support datetime format parsing

### ISSUE THREAD

**Issue by randerzander** [rapidsai/custrings#222]
Pandas DataFrames support [a variety of string->datetime formatting](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html).

For initial support of parsing string formatted datetimes with cuStrings, we should target the folliowing:
```
>>> pd.to_datetime('13000101', format='%Y%m%d', errors='ignore')
datetime.datetime(1300, 1, 1, 0, 0)
>>> pd.to_datetime('13000101', format='%Y%m%d', errors='coerce')
NaT
```
The above examples pass a static string, but should also support passing a Series/nvStrings type, where the datetime parsing is applied to each entry.

We should parse to cuDF's datetime64 numeric format, which I believe is based off [numpy's datetime64 type](https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html). @kkraus14 can confirm.

Per offline discussion, there is concern about adding non-core string functionality in the `nvstrings`  module, partly based on module size, and partly in the interest of separating of logical concerns. Given there will be some coalescing of the Python APIs when cuStrings merges with cuDF, for now, I suggest creating an `nvdate` module to implement this functionality.

**Comment by davidwendt** [comment]
Propose one level of staging the function here is to support the non-locale specific format specifiers first. The specifiers for Python/Pandas date/time are listed in this section: https://docs.python.org/3.7/library/datetime.html#strftime-and-strptime-behavior
The subset of specifiers (non-locale-dependent) are listed here:

- %d - day of month
- %m - month
- %y,%Y - year
- %H,%i - hour
- %M - minute
- %S - seconds
- %f - microseconds
- %z - UTC offset

Other number-only specifiers that may or may not be important:

- %w - weekday
- %j - day of the year
- %U,%W - week number of the year

The remaining specifiers are locale-specific with month names, week names and abbreviations for both as well as timezone names and default formats (%c and %x/%X). Also, if using %I specifier for 12-hour format, it may be necessary to support at least %p for `AM` and `PM` (as passed parameters perhaps).

The locale-specific features could be added as a separate item of work. Need some thought on how to provide these strings from Python's locale or the C++ standard-library locale functions (or as parameters).

**Comment by davidwendt** [comment]
In PR #260 the `int2timestamp` and `timestamp2int` methods take a `format` parameter (string of specifiers) along with more supported `units` values.

The specifiers supported are as documented in the previous comment above: `%Y,%y,%m,%d,%H,%I,%M,%S,%f,%z`. In addition the `%p` specifier is supported but only recognizes the 2 characters AM or PM. This is necessary for supporting `%I` 12-hour format.
None of the other format specifiers are supported as described previously. Support for these can be added by opening a future issue if necessary. If a format is not provided, the default format used is the following ISO8601 format: `%Y-%m-%dT%H:%M:%SZ`

Along with the new `format` argument, the `units` parameter now includes more time values:
- Y - years
- M - months
- D - days
- h - hours
- m - minutes
- s - seconds
- ms - milliseconds
- us - microseconds
- ns - nanoseconds

This is in keeping consistent with the numpy `datetime64` types defined here: https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html#datetime-units
The integer values are converted to/from these units using the format specified.
