### ISSUE TITLE
[BUG] cat doesn't accept a list of strings

### ISSUE THREAD

**Issue by beckernick** [rapidsai/custrings#227]
### Description
The [documentation](https://rapidsai.github.io/projects/nvstrings/en/0.3.0/api.html#nvstrings.nvstrings.cat) for `cat` suggests it can accept a list of strings, but it appears to require passing an nvstrings object itself.

### Example
```
strings = ['this is my favorite', 'book on my bookshelf']
d1 = nvstrings.to_device(strings)
d2 = nvstrings.to_device(strings)
d3 = nvstrings.to_device(strings)
print(d1.cat(d2, sep='__'))
print(d1.cat([d2, d3], sep='__'))
['this is my favorite__this is my favorite', 'book on my bookshelf__book on my bookshelf']
[None, None]
```

### Expected Behavior

As a user, I'd like to concatenate multiple nvstrings objects at once. I can loop through and update in place, but passing a list would be nice and similar to other nvstrings methods. If this is not desirable, we can instead update the documentation to reflect the need to pass a single nvstrings object.

**Comment by davidwendt** [comment]
Supporting a list of nvstrings is not intended.
The documentation says it can accept a list of `str` and not a list of `nvstrings` objects:
```
print(d1.cat(strings, sep='__'))
['this is my favorite__this is my favorite', 'book on my bookshelf__book on my bookshelf']
```
You can chain the methods if that helps:
```
print(d1.cat(d2,sep='__').cat(d3,sep='__'))
['this is my favorite__this is my favorite__this is my favorite', 'book on my bookshelf__book on my bookshelf__book on my bookshelf']
```

**Comment by beckernick** [comment]
Thanks @davidwendt. I misunderstood the documentation, but that makes sense.

Your example is essentially what I ended up doing in #224 with a loop. If this isn't intended to be supported without a loop/chaining, that's fine. Closing.
