### ISSUE TITLE
[DOC] Update nvtext.contains_string docstring to reflect Boolean types

### ISSUE THREAD

**Issue by beckernick** [rapidsai/custrings#236]
The [docstring](https://github.com/rapidsai/custrings/blob/8ab1b4b34aecbb9813c80d0abde3e8a1d768a067/python/nvtext.py#L75) for `contains_string` indicates that a device pointer expects a device array of type np.int32, when in fact it should be of type np.bool or np.int8

**Comment by davidwendt** [comment]
Fixed with changes in #273
