### ISSUE TITLE
[FEA] Support multiple delimiters in split, rsplit, etc.

### ISSUE THREAD

**Issue by randerzander** [rapidsai/custrings#242]
For any nvstrings function which accepts a `str` delimiter:
split, rsplit, split_record, rsplit_record, partition, rpartition

we should also support passing a list of `str` delimiter tokens. This can be the basis for future work creating more complex tokenization functions in `nvtext`.

**Comment by davidwendt** [comment]
I do not recommend using split for tokenizing in general though I know there cases where it makes sense. I'd prefer to make a new `tokenize()` method on nvtext that takes a string of delimiters.

**Comment by davidwendt** [comment]
Just to clarify. Would the delimiters be individual characters or a list of strings?
The delimiter parameter could be a str which can be a single or multiple characters.
If multiple strings are required, then the delimiter parameter would be string list or nvstrings instance.

**Comment by randerzander** [comment]
The delimiters would be a list of strings, some being individual characters, and some being multiple characters.

From a Python perspective, there are ways to handle arguments which are sometimes a single string, versus a list of strings.

However, I'm closing per @davidwendt 's comments regarding an `nvtext` focused `tokenize()` approach instead of using `nvstrings` functions.
