### ISSUE TITLE
[BUG] NVStringsImpl.setMemoryBuffer memory leak

### ISSUE THREAD

**Issue by JinHai-CN** [rapidsai/custrings#243]
if NVstringsImpl object memory buffer isn't empty, setMemoryBuffer will lead to the memory leak when new memory buffer is assigned and old memory buffer isn't free.

**Comment by davidwendt** [comment]
This was coded this way on purpose. I'm not aware of any condition where this will happen. If this condition occurs it should likely be an assert.

**Comment by JinHai-CN** [comment]
If some guy use the API when memory buffer isn't empty, no any error/exception/assert will be raised. This kind of memory leak will be very hard to find. Why not add protection?

**Comment by davidwendt** [comment]
Just verifying that there is no actual memory leak then.

**Comment by JinHai-CN** [comment]
Checked, no actual memory leak.

**Comment by davidwendt** [comment]
No memory leak.
