### ISSUE TITLE
[FEA] isempty 

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/custrings#249]
## Description

As a user i would like a function like `isempty` , where the function returns an array of boolean values with True for non empty strings. 

This will be super useful in workflows where we do some text processing and filter strings after some processing.

### Definition of <strike>non</strike> empty:
I believe we can follow python bool casting and consider the following to be <strike>non </strike>empty strings:

Code
```python
print(bool("")) #  "" (empty string)
print(bool(None)) # None (null string)
```
Output
```python
False
False
```
Edit: Both are empty strings. I wrote non empty by mistake.

**Comment by davidwendt** [comment]
Just for my reference, the bool cast/convert operator is defined here: https://docs.python.org/3.7/reference/datamodel.html#object.__bool__
Adding an `isempty` method should not be difficult.

**Comment by VibhuJawa** [comment]
Updated the issue. These should be considered as empty. Sorry for the confusion.

**Comment by davidwendt** [comment]
The bool casting property does not return an array of booleans:
```
>>> bool(['a','b'])
True
>>> bool(['a',None])
True
>>> bool([None,None])
True
>>> bool(['',''])
True
```
Only a single boolean is returned. 
So rather go with an explicit method like `is_empty` as proposed
