### ISSUE TITLE
[BUG] Replace cudaDeviceSynchronize with cudaStreamSynchronize

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/custrings#252]

**Comment by davidwendt** [comment]
Also, see if we can minimize usage. For example, if no copy back to the host then no sync is required.

**Comment by fynv** [comment]
Hey, I've just noticed this. IMO cudaDeviceSynchronize / cudaStreamSynchronize  are not nessessary at all but for timing. The syncrhonized memory copies (cudaMemcpy) will gurantee the correctness.

**Comment by davidwendt** [comment]
Closed by #255
