### ISSUE TITLE
[BUG] float to string rounds and converts to scientific notation without documentation

### ISSUE THREAD

**Issue by beckernick** [rapidsai/custrings#277]
`ftos` and `dtos` round floats and also convert large floats to scientific notation without mentioning this in the docs. We should either update the docs or the behavior, as its not consistent with Python's `str` behavior.

```python
import nvstrings
s = [0, 103, -2548485929, 9248.482]
print(nvstrings.ftos(s).to_host())
['0', '103', '-2.548485888e+09', '9248']

```

EDIT: When you use numpy floats, this doesn't happen. I believe Python default float is fp64 but slightly different from numpy

**Comment by davidwendt** [comment]
Added comments in nvstrings.py about scientific notation in #278
