### ISSUE TITLE
[FEA] `unique` method for NVStrings

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/custrings#290]
Add a `unique` method in NVStrings that returns the number of unique nvstrings provided. 

Would help with some groupby aggregations being performed on strings with workflows I'm working on right now. 

Would also help with multi column groupby (with multi-index support). https://github.com/rapidsai/cudf/issues/1570

**Comment by davidwendt** [comment]
Can you provide an example of what you are looking for here?

**Comment by ayushdg** [comment]
I don't think this method is actually needed as nvcategory already provides this functionality. Sorry for the confusion.
`nvcategory.from_strings(cudf.Series).keys()`

**Comment by thomcom** [comment]
We still need a unique method on the `StringColumn` class. It can use the function from `nvcategory`. Want to pursue a PR?
