### ISSUE TITLE
support for IPv6 in ip2int

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/custrings#309]
It would be a nice to have this function to support IPv6 addresses too. Currently it has support for IPv4 addresses.

Expected example:
```
>>> import nvstrings
>>> s = nvstrings.to_device(["192.168.0.1","0000:0000:0000:0000:0000:0000:0a00:0001"])
>>> print(s.ip2int())
[3232235521, 167772161]
```

**Comment by davidwendt** [comment]
The IPv6 address elements are in hex resulting in 128-bit number. So it is not possible to convert to int (32-bit) or even to a long (64-bit).
Best option may be to split the string into 2 or more columns first and use htoi() on the sub-parts. 
Given that, I'm inclined to close this issue.

**Comment by BartleyR** [comment]
What @davidwendt said should be fine. The logic to handle abbreviated IPv6 addresses could be written around this as well.

**Comment by galipremsagar** [comment]
Cool, will have the logic implemented in that way. Closing this issue. Thanks for the input @davidwendt 👍
