### ISSUE TITLE
nvstrings and libnvstrings dependency ?

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/custrings#317]
While I was testing #310 , I've installed [nvstrings ](https://anaconda.org/rapidsai-nightly/nvstrings)using the following command:
`conda install -c rapidsai-nightly nvstrings=0.8.0a`

After running a normal regular expression match code I get the following error:
ValueError                                Traceback (most recent call last)
ValueError: parallel_for failed: an illegal memory access was encountered

The above exception was the direct cause of the following exception:
```

SystemError                               Traceback (most recent call last)
<ipython-input-14-7f125bdeea7b> in <module>
      7 unspecified_df = cycudf.df.copy()
      8 st = time.time()
----> 9 is_unspecified(unspecified_df)
     10 et = time.time()
     11 gpu_time = et - st

<ipython-input-14-7f125bdeea7b> in is_unspecified(df)
      1 def is_unspecified(df):
      2     unspecified_REGEX = '^0\.0\.0\.0$'
----> 3     return df['network'].data.match(unspecified_REGEX)
      4 
      5 # is_unspecified(cycudf.df)

/conda/envs/rapids/lib/python3.6/site-packages/nvstrings.py in match(self, pat, devptr)
   1947 
   1948         """
-> 1949         rtn = pyniNVStrings.n_match(self.m_cptr, pat, devptr)
   1950         return rtn
   1951 

SystemError: <built-in function n_match> returned a result with an error set
```

But after I also installed [libnvstrings](https://anaconda.org/rapidsai-nightly/libnvstrings) with the following command:

`conda install -c rapidsai-nightly libnvstrings=0.8.0a`

The above error vanishes and I was able to validate the fixed bug. So my question is do we have to add this version as a dependency to nvstrings ? Asking this because I had to manually install this version of libnvstrings to resolve the above exception.

**Comment by davidwendt** [comment]
@kkraus14 Could use your opinion on this one.

**Comment by kkraus14** [comment]
We already pin the version, but this is likely a situation of updating to a newer nightly of `nvstrings` but not `libnvstrings`. I don't think we need to guard against this as it would be a pain since versioning is based on git tag.
