### ISSUE TITLE
Regex performance regression of about 2x between nightly 0.8 (2019-06-06) and 0.7

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/custrings#318]
Until yesterday the following code ran for `1min 17s`

```
%%time
def is_ip_string(df):
    s = df['network'].data
    REGEX = r"\b((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4}\b"
    df['is_ip_string'] = s.match(REGEX)
    return df


is_ip_df = global_df.map_partitions(is_ip_string)

wait(is_ip_df.persist())
```

The data in the global_df['network'] are IP strings..like :
```
>>> global_df.head()
           network    
0    73.101.53.217
1     5.254.19.123 
2  108.167.158.211
3  108.167.158.212
4    84.204.40.220  
```

The number of records are 1Billion.

But after installing latest nightly of [nvstrings](https://anaconda.org/rapidsai-nightly/nvstrings), I see that it take twice the amount of time to execute. With latest nightly it takes `2min 52s`, whereas previously it completed execution in `1min 17s`

Note: I didn't change my dask-cudf version I just installed the latest nightly of nvstrings.

**Comment by VibhuJawa** [comment]
Can, confirm a similar  performance regression  in `0.8 (nightly)` vs `0.7`(stable) in my wiki workflow.  

Regex computations now seems to be taking `2682.38 s` vs  previously taking `1094.66 s` .

**Comment by davidwendt** [comment]
@VibhuJawa We were not able to reproduce the 2x degradation you are seeing. The change made in #331 essentially reverts the stack-size change made previously in 0.8 so hopefully you will see an improvement.

**Comment by galipremsagar** [comment]
> Until yesterday the following code ran for `1min 17s`
> 
> ```
> %%time
> def is_ip_string(df):
>     s = df['network'].data
>     REGEX = r"\b((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4}\b"
>     df['is_ip_string'] = s.match(REGEX)
>     return df
> 
> 
> is_ip_df = global_df.map_partitions(is_ip_string)
> 
> wait(is_ip_df.persist())
> ```
> 
> The data in the global_df['network'] are IP strings..like :
> 
> ```
> >>> global_df.head()
>            network    
> 0    73.101.53.217
> 1     5.254.19.123 
> 2  108.167.158.211
> 3  108.167.158.212
> 4    84.204.40.220  
> ```
> 
> The number of records are 1Billion.
> 
> But after installing latest nightly of [nvstrings](https://anaconda.org/rapidsai-nightly/nvstrings), I see that it take twice the amount of time to execute. With latest nightly it takes `2min 52s`, whereas previously it completed execution in `1min 17s`
> 
> Note: I didn't change my dask-cudf version I just installed the latest nightly of nvstrings.


@davidwendt 
I've picked the newly merged code and for me the time taken has further increased. The above code now takes `3min 5s` to run.

I can provide the data if needed or sync up with you offline on this.

**Comment by VibhuJawa** [comment]
So, the performance seems to be now same as 0.7 but the `peak memory usage` aswell as `memory usage` after operations seems to be much worse. 

` 4167 mIB` vs `6415 miB`

See [0.7_gist](https://gist.github.com/VibhuJawa/677498a5b1b7610330212d0b147a24b6)

See [0.8_gist](https://gist.github.com/VibhuJawa/5c18627f011962e44aa5a000ef2569aa)

@davidwendt , Can you run the above and confirm you are seeing a similar memory increase. 

Also, even after deleting the nvstrings we have a lot of memory usage.

**Comment by davidwendt** [comment]
Added comment in #333. I've tried this on my machine and see the memory usage similar to your description. The changes in #334 seemed to fix this.

**Comment by galipremsagar** [comment]
> Until yesterday the following code ran for `1min 17s`
> 
> ```
> %%time
> def is_ip_string(df):
>     s = df['network'].data
>     REGEX = r"\b((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4}\b"
>     df['is_ip_string'] = s.match(REGEX)
>     return df
> 
> 
> is_ip_df = global_df.map_partitions(is_ip_string)
> 
> wait(is_ip_df.persist())
> ```
> 
> The data in the global_df['network'] are IP strings..like :
> 
> ```
> >>> global_df.head()
>            network    
> 0    73.101.53.217
> 1     5.254.19.123 
> 2  108.167.158.211
> 3  108.167.158.212
> 4    84.204.40.220  
> ```
> 
> The number of records are 1Billion.
> 
> But after installing latest nightly of [nvstrings](https://anaconda.org/rapidsai-nightly/nvstrings), I see that it take twice the amount of time to execute. With latest nightly it takes `2min 52s`, whereas previously it completed execution in `1min 17s`
> 
> Note: I didn't change my dask-cudf version I just installed the latest nightly of nvstrings.

@davidwendt, Thanks for fixing this. I can confirm that this issue is now fixed and now it takes 1min 15s to run. 👍  Hence closing this issue.
