### ISSUE TITLE
[FEA] urls encode & decode support

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/custrings#321]
In large datasets we usually have scraped data records from websites which would be having URL's in encoded format. Such kind of encoded URLs need to be handled as part of data cleaning and in rapids for now workaround is to find the exact encoded literals and replace them with decoded literals. Sample code for one such literal decoding:

```
import cudf
x = cudf.DataFrame({'path':["www.nvidia.com%2Frapids%2F"]})
print(x.path.data.replace('%2F','/'))
```

Output:
```
['www.nvidia.com/rapids/']
```

But there are many such encodings: [reference link](https://www.w3schools.com/tags/ref_urlencode.asp)
So it would be good to have a `encode_urls` and `decode_urls` functionality embedded into custrings.

**Comment by davidwendt** [comment]
Just need some clarification on this. Generally url-encoding is for url parameters and not for the url address part. You usually see `http://www.nvidia.com/rapids?parm1=dave%2Fvalue1` The %2F indicates a forward slash but there are 3 other forward-slashes that are not encoded. This works fine for decoding. But re-encoding this string will escape all slashes.

This is how url-encoders work in libraries for Javascript, Java, C#, etc. They do not interpret the address part any different. This is in case you want to encode a url as a parameter like `http://www.nvidia.com/rapids?url1=other.site.com%2Fdownloads%2Ffile1.zip`

Therefore a *url-decode* of `http://www.nvidia.com%2Frapids%2F` would be `http://www.nvidia.com/rapids/` but a *url-encode* of that result would be `http%3A%2F%2Fwww.nvidia.com%2Frapids%2F`

Perhaps only url-decode would be sufficient right now?

**Comment by galipremsagar** [comment]
So the use-case here was The real-world dataset had the entire string(strings can be file paths too instead of URLs) encoded. 

So in pandas the equivalents to the requirement would be:
encode: https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote
decode: https://docs.python.org/3/library/urllib.parse.html#urllib.parse.unquote

sample:
```python
urllib.parse.quote("http://www.hellow.com", safe='')
'http%3A%2F%2Fwww.hellow.com'

urllib.parse.unquote("http%3A%2F%2Fwww.hellow.com")
'http://www.hellow.com'

urllib.parse.quote("/home/pgali/nfs",safe='')
'%2Fhome%2Fpgali%2Fnfs'

urllib.parse.unquote('%2Fhome%2Fpgali%2Fnfs')
'/home/pgali/nfs'

```

**Comment by davidwendt** [comment]
Ok, thanks.
