### ISSUE TITLE
NVStrings::to_host may overwrite input pointers

### ISSUE THREAD

**Issue by harrism** [rapidsai/custrings#330]
The input to `to_host()` is a an array of pointers to char arrays. This line, if called, will set the pointers in the array to all zeros. Since these pointers point to arrays allocated outside of NVStrings, this might be surprising to the caller, and lead to lost memory. 

https://github.com/rapidsai/custrings/blob/fd4d072fc518de400c88890069c8739183e2563f/cpp/src/NVStrings.cu#L291

This line will have the same ill effect:
https://github.com/rapidsai/custrings/blob/fd4d072fc518de400c88890069c8739183e2563f/cpp/src/NVStrings.cu#L349

The documentation doesn't mention these side effects, so I assume they are bugs.

**Comment by davidwendt** [comment]
This is to communicate which strings are null. I can add a mention in the doxygen.

**Comment by harrism** [comment]
But communicating it this way is overwriting pointers, which can cause memory leaks if they are the only copy of the pointers that the user has. 

I think this would be common. Or at least this is how I interpreted that I would have to get the data to the host.
```
char ** data = new char *[keys_size];
char ** data = new char *[keys_size];
int * byte_sizes = new int[keys_size];
keys->byte_count(byte_sizes, false);
for(size_t i=0; i<keys_size; i++){
  data[i]=new char[std::max(1, byte_sizes[i])]; // use max to ensure even null strings have space
}
keys->to_host(data, 0, keys_size);
```

In this case, calling `to_host` may result in one or more of the elements of `data` being overwritten by `0`, resulting in memory leaks.

You need to write into the allocated memory, not write the pointer. For null strings, just write the null string (a zero) into the first byte of the output string.

So for example, I think https://github.com/rapidsai/custrings/blob/fd4d072fc518de400c88890069c8739183e2563f/cpp/src/NVStrings.cu#L349

Should be `list[idx][0] = 0`. 

And I think https://github.com/rapidsai/custrings/blob/fd4d072fc518de400c88890069c8739183e2563f/cpp/src/NVStrings.cu#L291

Should be replaced by a loop:
`std::for_each(list, list + count, [idx = 0] mutable () { list[idx++][0] = 0; }`
(or equivalent for loop)

**Comment by davidwendt** [comment]
Placing a null at the beginning of the string makes it an empty string which is different than a null string.
For example, in Python there is a difference between [None] and ['']. The first is a null string and the second is an empty string.
Regardless, I agree modifying the pointers is bad since they could be allocated individually and thereby cause a memory leak in the host. The null strings can be identified using the bitmask methods so I think it best to leave the pointer and data unchanged and require the caller to check the bitmask for nulls instead.

**Comment by harrism** [comment]
There's also the `byte_count` method which I believe returns `-1` for null so the user can use that. So yes I agree you could safely leave the pointer and data unchanged for null strings.

**Comment by harrism** [comment]
BTW, for posterity, here's some code I didn't write that I ran into that is broken by this issue: 
https://github.com/rapidsai/cudf/blob/34a59206a49cac1fb343242d717126d99b4357e2/cpp/tests/utilities/nvcategory_utils.cu#L132-L150

The last line fails because it tries to create a vector of std::string from an array of strings, but some of the input strings are `nullptr` after the call to `NVStrings::to_host` when the input column has nulls. If they were left as empty strings (as they are once #335 is merged), this code would work fine.
