### ISSUE TITLE
[FEA] value_count for nvcategory

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/custrings#337]
#### value_count for nvcategory

Would like to have a function that gives number of values pointing to each key.

Dummy example:
```python
c = nvcategory.to_device(["aa","bb","bb","cc"])
print(c.value_count())
```
Output:
```python
[1,2,1]
```

Context: 
Categorization based on frequency of strings is a common operation in workflows.  Implementing this will help with that .

It can also help to close the issue :  https://github.com/rapidsai/cudf/issues/1951

**Comment by randerzander** [comment]
nvcategory will eventually be fully integrated into cudf, so instead of us creating a special nvcategory.value_counts method, I think you should use the existing workaround of writing nvcategory values into a cuDF Series and calling value_counts on that.
