### ISSUE TITLE
[BUG] Alphabetical sort should order Nones at the end

### ISSUE THREAD

**Issue by beckernick** [rapidsai/custrings#339]
May not matter, but to match pandas's sort functionality calling `sort` should order the non-None values ahead of the None values by default.

This may not matter much in cuDF land as calling `sort_values` on a StringColumn does already place the Nones at the end, like pandas. This functionality wouldn't change, as it's configurable in cuDF/pandas

```
import nvstrings
import pandas as pd
​
s = nvstrings.to_device(['a','b','a',None,'c'])
print(s.sort(2))
print(pd.Series(['a','b','a',None,'c']).sort_values())
[None, 'a', 'a', 'b', 'c']
0       a
2       a
1       b
4       c
3    None
dtype: object
```

https://github.com/rapidsai/cudf/blob/f7631e7782ca6ecc703903a2d3d8770761873b68/python/cudf/dataframe/string.py#L593-L597

**Comment by davidwendt** [comment]
The `sort()` method includes a parameter called `nullfirst` which can be used to place the nulls at the beginning or the end. https://github.com/rapidsai/custrings/blob/e173112124ea90c90512f1ebca809d97a779f4da/python/nvstrings.py#L2273
This was added by request in a previous release. See #117 and #125.

**Comment by beckernick** [comment]
👍 oversight on my part to not notice that. We can probably forget this. Closing now. Thanks @davidwendt
