### ISSUE TITLE
Dask not support librmm_cffi

### ISSUE THREAD

**Issue by MikeChenfu** [rapidsai/custrings#348]
I use `librmm.device_array` to write nvcategory values into a device array and I use `dask` to map the function into workers. But I got the below error.

> distributed.protocol.pickle - INFO - Failed to serialize <function process at <br/> 0x7f96f78b8840>. Exception: can't pickle CompiledFFI objects

It seems that the function containing `librmm.device_array` cannot be serialized.
I really appreciate if anyone has suggestions about this problem.

**Comment by davidwendt** [comment]
This repo does not use `librmm.device_array` in any of its methods.
You may want to open an issue on the `serialize` method in `cudf` at https://github.com/rapidsai/cudf
