### ISSUE TITLE
[FEA] nvstrings.replace should support either single, or list of `pat`

### ISSUE THREAD

**Issue by randerzander** [rapidsai/custrings#365]
In text processing it's common to remove many tokens or "stop-words" by using `str.replace(word, '')`.

It's also common to use `str.replace(word1, '').replace(word2, '').replace(wordN, '')`. Most workarounds to this annoying pattern involve creating a regex.

We've also evaluated using regexes to perform this logic in nvstrings, but the longer/more complex an nvstrings regex is, the lower performance it will be.

If we can have `nvstrings.replace` support a list of target substrings that need to be replaced, and have that operate faster than the regex equivalent, that would also be a big ease of use improvement.

Using replace today:
```
>>> strs = nvstrings.to_device(['hello there, good friend', 'hi there!'])
>>> clean = strs.replace(',', '').replace('!', '')
>>> print(clean)
```

Result:
```
['hello there good friend', 'hi there']
```
Proposed new use:
```
clean = strs.replace([',', '!'], '')
```

The above would replace all target substrings with the same replacement value. It may also be worth considering letting the `repl` argument be a corresponding list of replacement tokens, or combining `pat` and `repl` into a dict with key-value target/replacement pairs.

**Comment by davidwendt** [comment]
The proposed method of passing multiple parameters should certainly be faster for large number of strings since the intermediate objects are not created and destroyed. Going to start without regex first.

**Comment by davidwendt** [comment]
First issue is the current `replace` parameters in python which are `pat, repl, n=-1, regex=True`
The `n` parameter is how many times the `pat` will be replaced by `repl` before stopping for each string.
For multiple targets, I think this parameter is confusing. Does it mean to replace `n` times per target or per string. For example:
```
strs = nvstrings.to_device(['hello there, good friend!', 'hi there!'])
clean = strs.replace(['e', '!'], '', n=3)
```
Does this replace 3 e's in the first string and not the '!'? Or does the count apply to each target?
I would like to ignore this parameter in this case. Or perhaps we should have a different function name for this.

**Comment by randerzander** [comment]
Given the growing complexity of overloading the existing `replace` function, I'm in favor of creating `multireplace`.

I _could_ see it being useful for `n` itself to be a list corresponding with the items in `pat`, but am fine not supporting it until a usecase needs it.

**Comment by davidwendt** [comment]
I'm working on this in 3 parts:
1. replace strings -- this is not regex and not tokens
2. replace with regex -- use pattern to find strings to replace
3. replace tokens -- use delimiter to find tokens/strings to replace
The third option may be a faster than regex as way to remove/replace words from a _prepared_ set of strings.

**Comment by davidwendt** [comment]
Methods added in #371:
`nvstrings replace_multi(pats, repls, regex)` - this is 2 different C++ methods one with regex and one without
`nvtext replace_tokens(strs, tgts, repls, delimiter)` - this replaces individual tokens and is as alternative to using regex for specific cases
As expected, the `replace_multi` is significantly faster than chaining `replace()` methods with individual strings.
Also, I tested removing stop-words (~100 words/tokens) from 1M strings (~10 tokens each) and the `replace_tokens` is over 100x faster than its `replace_multi` regex counterpart.
