### ISSUE TITLE
[FEA] nvcategory support for returning keys from a list of values

### ISSUE THREAD

**Issue by beckernick** [rapidsai/custrings#366]
Given an nvcategory object with defined keys and values, I'd like to be call a function that accepts a list of a values and returns a list of the same size (in the same order) in which each element is the key corresponding to that value from the nvcategory object. This is not trying to translate base on indices, but based on the encoding.

This would be very useful for label encoding / inverse label encoding (transforming back).

As an example:

```python
import nvstrings
import nvcategory
​
s = nvstrings.to_device(['a','q','c','b'])
s_cat = nvcategory.from_strings(s)
print(s_cat.keys(), s_cat.values())
​# ['a', 'b', 'c', 'q'] [0, 3, 2, 1]

# example API -- transform is not the right name probably
s_cat.decode([0,1,2])
# ['a', 'b', 'c']
```

We'd want to return an array of the same size as the input array, so if a value did not have a corresponding key we'd need to return some sort of null signifier.

**Comment by davidwendt** [comment]
Checkout the `gather_strings` method:
```
import nvcategory
c = nvcategory.to_device(["eee","aaa","eee","dddd"])
print(c.keys())
```
```
['aaa','dddd','eee']
```
```
print(c.values())
```
```
[2, 0, 2, 1]
```
```
print(c.gather_strings([0,2,0]))
```
```
['aaa','eee','aaa']
```
Let me know if this does not match what you are looking for here.

**Comment by beckernick** [comment]
Thanks David. For some reason in my mind this was not tied to the index of the keys but of the values (i.e., gather the strings currently at index position 0, 2, 0, etc.). It's clearly stated in the docs that the indexes are for the keys, but the example also works if the indexes were for the individual strings themselves. 

@deltadu , I believe this should allow you to rework `LabelEncoder.inverse_transform` to simply use  `LabelEncoder._cats.gather_strings(encoded_data)` internally to the class, right?

**Comment by beckernick** [comment]
@davidwendt as a note, passing an index to `gather_strings` that is out of bounds for the number of keys causes a segfault. We should protect users from that.

@deltadu , this shouldn't block your PR, as you'll want to raise a ValueError if the `encoded` array passed to inverse_transform contains unseen values (which you already do). You'll just want to make sure to do before calling `gather_strings`.
