### ISSUE TITLE
[FEA] Multi char replace

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/custrings#374]
As a user, I would like to have a multi-char  replace where we replace multiple occurrences of the input characters with a single occurrence of replacement char. 

This function will be especially useful for replacing multiple `white space` like characters with a `single space` . 

#### Example api rquested:

```python
input_strs = input_strs.replace_multi_char( ['\t', '\r', '\n' , '\f'] ,  '  ')
```

#### Current way to do this:
Currently we achieve this behavior via a series of `single char` replaces or with  a `combined  regex replace` . 
 
Example:

```python
import nvstrings
import nvtext

test_sentence = 'This\f  is \t\t   an \n example\r\n'
input_strs = nvstrings.to_device([test_sentence])
input_strs = input_strs.replace(r"\s+", ' ')

## essentially equivalent to #[\t\r\n\f] 
print(input_strs)

```
Output:
```python
['This is an example ']
```

**Comment by davidwendt** [comment]
There is a concept called _normalize-spaces_ in various places (mostly in XPath). The concept is to remove extra whitespace between words/tokens in a string and also trim whitespace from the beginning and end of the string. 
My proposal is to create an `NVText::normalize_spaces` method that performs this function. My initial testing showed that it can run 2x-10x faster than the equivalent regex replace method (depending on the number of strings) with the side-effect of trimming whitespace from the beginning and end of each string.

Using the example from the description:
```
import nvstrings
import nvtext

test_sentence = 'This\f  is \t\t   an \n example\r\n'
input_strs = nvstrings.to_device([test_sentence])
input_strs = nvtext.normalize_spaces(input_strs)

print(input_strs)
```
Output:
```
['This is an example']
```
Note the trailing whitespace is also removed.

**Comment by davidwendt** [comment]
Closing this per normalize-spaces feature added in #386
