### ISSUE TITLE
`timestamp2int` sometimes gives wrong result

### ISSUE THREAD

**Issue by shwina** [rapidsai/custrings#377]
Here's a reproducer:

```
In [15]: for i in range(100_000): 
    ...:     x = nvstrings.nvstrings.timestamp2int(nvstrings.to_device(["2001-10-10"]))[0] 
    ...:     if x != 1002672000: 
    ...:         print(x) 
```

**Comment by davidwendt** [comment]
You must specify the date-time format if your strings are not in ISO8601 format. There is no format checking on individual strings and the format will not be guessed from the strings provided. Here is the correct usage for the example you provided:
```
x = nvstrings.to_device(["2001-10-10"]).timestamp2int("%Y-%m-%d")[0]
```

**Comment by shwina** [comment]
Thanks @davidwendt!
