### ISSUE TITLE
[BUG] stod() does not convert properly

### ISSUE THREAD

**Issue by drabastomek** [rapidsai/custrings#388]
When trying to parse a string like '-122.33644763' to float64 I get -36.43710...

Here's a minimal example of what I'm doing:

    def extractLon(location):
        lon = location.str.extract('([0-9\.\-]+) ([0-9\.]+)')[0]
        return lon
    
    def extractLon_decimal(location):
        lon = location.str.extract('([0-9\.\-]+) ([0-9\.]+)')[0]
        return lon.str.stod()
    
    data = [
          'POINT (-122.33644763 47.61672619)'
        , 'POINT (-122.34481093 47.61765602)'
        , 'POINT (-122.34293648 47.61700881)'
    ]
    
    df = cudf.DataFrame({'Location': data})
    
    df['LON']     = extractLon(df['Location'])
    df['LON_dec'] = extractLon_decimal(df['Location'])
    
    print(df[['Location', 'LON', 'LON_dec']])

What prints out is the following:

                                Location            LON            LON_dec
    0  POINT (-122.33644763 47.61672619)  -122.33644763 -36.43710170999999
    1  POINT (-122.34481093 47.61765602)  -122.34481093 -36.44546500999999
    2  POINT (-122.34293648 47.61700881)  -122.34293648       -36.44359056
    time: 151 ms

**Comment by ayushdg** [comment]
I can confirm reproducing the issue. Here is another reproducer (inspired from the example above) using the nvstrings module

```
import nvstrings as nvs

a = ["44.12345678","-122.33644782"]
b = nvs.to_device(a)
print(b)
b.stod()

['44.12345678', '-122.33644782']
[1.17378382, -36.437101899999995]
``` 
Also it seems like if I reduce the number of decimals the conversion works fine:
```
import nvstrings as nvs

a = ["44.1234567","-122.3364478"]
b = nvs.to_device(a)
print(b)
b.stod()

['44.1234567', '-122.3364478']
[135]:
[44.123456700000006, -122.33644780000002]
```

Thanks for the issue @drabastomek :)
